version: '3'
services:
    web:
      build: 
        context: .
        dockerfile: Dockerfile.dev
      ports: 
        - "3000:3000"
      volumes: 
        - /app/usr/node_modules
        - .:/app/usr   
    tests:    
      build: 
        context: .
        dockerfile: Dockerfile.dev
      volumes: 
        - /app/usr/node_modules
        - .:/app/usr
      command: ["npm", "run", "test"]        